Addition of a Hibernate projection about the sms sending date in a SQL request with DISTINCT in order to avoid having the error 'unknown error 500' in the web browser.
The related Http response :
java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'smsuapi.this_.SMS_DATE' which is not in SELECT list; this is incompatible with DISTINCT.